# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b84451b5c89672b72f556ff9c683d9b8cfd84d556819fc64a76a8e183fe17c0f7327806916b17822c1abe371c3c182e9dd0da4dd7cb277d16d8396a3760f013

test:
  secret_key_base: c8b574430d2ee868d9340ddceff56a557e68850ce80e0e094cc49f37c56c70224c6ba8119b0241cf9ea5b9a719677485d5ea8601d495b1d8f5d680bc288c433a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
